<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bitum.Contracts\Bitum.Contracts.csproj" />
    <ProjectReference Include="..\Bitum.Domain\Bitum.Domain.csproj" />
  </ItemGroup>

</Project>
